# Generated by Django 5.1.1 on 2026-05-28 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='tittle',
            new_name='title',
        ),
    ]
